CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE expense (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         description VARCHAR(100) NOT NULL,
                         amount NUMERIC(38, 2) NOT NULL,
                         category VARCHAR(255) NOT NULL,
                         date DATE NOT NULL,
                         user_id BIGINT,

                         CONSTRAINT fk_expense_user
                             FOREIGN KEY (user_id)
                                 REFERENCES app_user(id),

                         CONSTRAINT chk_expense_category
                             CHECK (
                                 category IN (
                                              'FOOD',
                                              'TRANSPORT',
                                              'HOUSING',
                                              'ENTERTAINMENT',
                                              'HEALTH',
                                              'SHOPPING',
                                              'OTHER'
                                     )
                                 )
);